server:
  port: 8081
security.jwt.token.secret-key: ${SECRET_KEY}
spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId:
            clientSecret:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - emails
              - public_profile

app:
  oauth2:
    authorizedRedirectUris:
      - ${CLIENT_URL}/oauth2/redirect
      - ${CLIENT_URL}/oauth/redirect